#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


if [ -e /etc/profile.d/nix.sh ]
then
  source /etc/profile.d/nix.sh
fi

if ! [ -e /nix ] || ! command -v nix-env >/dev/null 2>&1
then
  "${BASEDIR}/nix/install" --daemon
fi

source /etc/profile.d/nix.sh

if ! command -v python3 && ! command -v python && ! command -v python2
then
  nix-env -i -A nixpkgs.python3Full
fi

if ! command -v git
then
  nix-env -i -A nixpkgs.gitAndTools.gitFull
fi
