#!/usr/bin/env bash


# Load our basic environment.
if [ -f ~/.env ] && [ -r ~/.env ]
then
  . ~/.env
fi


# Read our modular config.
if [ -d ~/.xprofile.d ]
then
  for file in ~/.xprofile.d/*
  do
    [ -f "$file" ] && [ -r "$file" ] && . "$file"
  done
fi
unset file





ibus-daemon -drx

# Dim after 10 minutes, lock 10 minutes later.
xset s 600 1200

# Turn on numlock.
numlockx on

# Set middle-button emulation.
for input in $(xinput --list | grep 'Logitech' | sed -r 's/.*\tid=([0-9]+)[^0-9].*$/\1/')
do
  xinput --set-prop "$input" "libinput Middle Emulation Enabled" 1
done

# Turn off touchpad.
xinput disable 'pointer:SynPS/2 Synaptics TouchPad'

# Activate Compose key.
setxkbmap -model evdev -layout us -option compose:lwin

# Swap caps lock and escape.
xmodmap ~/.config/speedswapper

# Printer applet.
system-config-printer-applet &

# Skype.
skypeforlinux &

xinput disable 'Yubico Yubikey 4 OTP+U2F+CCID'



# Read local overrides.
if [ -f ~/.xprofile.local ] && [ -r ~/.xprofile.local ]
then
  . ~/.xprofile.local
fi
