# This file is sourced by zsh for all shells.
# It cannot affect any input or output, and shouldn't assume that it's connected
# to a TTY.


# Load our basic environment.
if [ -f ~/.env ] && [ -r ~/.env ]
then
  . ~/.env
fi



# Create local TeX directories.
mkdir -p "${HOME}/"texmf >/dev/null 2>&1


# Environment variables.



# Connect to system qemu libvirtd by default.
export LIBVIRT_DEFAULT_URI="qemu:///system"

# Use st as the terminal.
if command -v st >/dev/null 2>&1
then
  export TERMINAL="st"
fi

# Local TeX packages.
export TEXMFHOME="${HOME}/texmf"


# Set the PATH-like variables.



# Set the PATH.



# FSlint utilities.
if [ -d "/usr/share/fslint/fslint" ]
then
  path+=("/usr/share/fslint/fslint")
fi





# TeX Live perl stuff.

if [ -d "/usr/share/tlpkg" ]
then
  perl5lib=("/usr/share/tlpkg" "$perl5lib[@]")
fi

if [ -d "/usr/share/texmf-dist/scripts/texlive" ]
then
  perl5lib=("/usr/share/texmf-dist/scripts/texlive" "$perl5lib[@]")
fi




# Force the variables tied to arrays to have unique elements.
typeset -U path


export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"



# Read our modular config.
if [ -d ~/.zshenv.d ]
then
  for file in ~/.zshenv.d/*
  do
    [ -f "$file" ] && [ -r "$file" ] && . "$file"
  done
fi
unset file

# Read local overrides.
if [ -f ~/.zshenv.local ] && [ -r ~/.zshenv.local ]
then
  . ~/.zshenv.local
fi
