# This file is sourced by zsh for all shells.
# It cannot affect any input or output, and shouldn't assume that it's connected
# to a TTY.


# Load our basic environment.
if [ -f ~/.env ] && [ -r ~/.env ]
then
  . ~/.env
fi








# Connect to system qemu libvirtd by default.
export LIBVIRT_DEFAULT_URI="qemu:///system"

# Use st as the terminal.
if command -v st >/dev/null 2>&1
then
  export TERMINAL="st"
fi








# Read our modular config.
if [ -d ~/.zshenv.d ]
then
  for file in ~/.zshenv.d/*
  do
    [ -f "$file" ] && [ -r "$file" ] && . "$file"
  done
fi
unset file

# Read local overrides.
if [ -f ~/.zshenv.local ] && [ -r ~/.zshenv.local ]
then
  . ~/.zshenv.local
fi
