# This file is sourced by zsh only for interactive shells.


# Read our modular config.
if [ -d ~/.zshrc.d ]
then
  for file in ~/.zshrc.d/*
  do
    [ -f "$file" ] && [ -r "$file" ] && . "$file"
  done
fi
unset file


# Read local overrides.
if [ -f ~/.zshrc.local ] && [ -r ~/.zshrc.local ]
then
  . ~/.zshrc.local
fi
